require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OfferingsController do

  def mock_offering(stubs={})
    @mock_offering ||= mock_model(Offering, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all offerings as @offerings" do
      Offering.stub(:all) { [mock_offering] }
      get :index
      assigns(:offerings).should eq([mock_offering])
    end
  end

  describe "GET show" do
    it "assigns the requested offering as @offering" do
      Offering.stub(:find).with("37") { mock_offering }
      get :show, :id => "37"
      assigns(:offering).should be(mock_offering)
    end
  end

  describe "GET new" do
    it "assigns a new offering as @offering" do
      Offering.stub(:new) { mock_offering }
      get :new
      assigns(:offering).should be(mock_offering)
    end
  end

  describe "GET edit" do
    it "assigns the requested offering as @offering" do
      Offering.stub(:find).with("37") { mock_offering }
      get :edit, :id => "37"
      assigns(:offering).should be(mock_offering)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created offering as @offering" do
        Offering.stub(:new).with({'these' => 'params'}) { mock_offering(:save => true) }
        post :create, :offering => {'these' => 'params'}
        assigns(:offering).should be(mock_offering)
      end

      it "redirects to the created offering" do
        Offering.stub(:new) { mock_offering(:save => true) }
        post :create, :offering => {}
        response.should redirect_to(offering_url(mock_offering))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved offering as @offering" do
        Offering.stub(:new).with({'these' => 'params'}) { mock_offering(:save => false) }
        post :create, :offering => {'these' => 'params'}
        assigns(:offering).should be(mock_offering)
      end

      it "re-renders the 'new' template" do
        Offering.stub(:new) { mock_offering(:save => false) }
        post :create, :offering => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested offering" do
        Offering.stub(:find).with("37") { mock_offering }
        mock_offering.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :offering => {'these' => 'params'}
      end

      it "assigns the requested offering as @offering" do
        Offering.stub(:find) { mock_offering(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:offering).should be(mock_offering)
      end

      it "redirects to the offering" do
        Offering.stub(:find) { mock_offering(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(offering_url(mock_offering))
      end
    end

    describe "with invalid params" do
      it "assigns the offering as @offering" do
        Offering.stub(:find) { mock_offering(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:offering).should be(mock_offering)
      end

      it "re-renders the 'edit' template" do
        Offering.stub(:find) { mock_offering(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested offering" do
      Offering.stub(:find).with("37") { mock_offering }
      mock_offering.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the offerings list" do
      Offering.stub(:find) { mock_offering }
      delete :destroy, :id => "1"
      response.should redirect_to(offerings_url)
    end
  end

end
